# SVM model 

### step 4 and 5 in readme

In [43]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score, cross_val_predict, RandomizedSearchCV
from sklearn.metrics import *
import numpy as np

In [44]:
# read hinge features for train data
x_hinge = np.load("featuresTrainDataSet/hinge_features.npy")
# read cold for train data
x_cold = np.load("featuresTrainDataSet/cold_features.npy")
# read hinge features for test data
x_hingeT = np.load("featuresTestData/hinge_features.npy")
# read cold features for test data
x_coldT = np.load("featuresTestData/cold_features.npy")
# read label for train data
y = np.load("featuresTrainDataSet/labels.npz")['label']
# label for test data
y_test = [0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1]



In [45]:
# Linear Kernel
clf = SVC(kernel='rbf', verbose=True, C=10) 

# Train the model using the train data set(hinge features)
clf.fit(x_hinge, y)

# Predict the response for train dataset
y_pred_hinge_train = clf.predict(x_hinge)



# Model Accuracy for train data set 
print("Accuracy:",accuracy_score(y, y_pred_hinge_train))
# print confusion_matrix
print(confusion_matrix(y,y_pred_hinge_train))
# print f1_score
f1_score(y,y_pred_hinge_train)


[LibSVM]Accuracy: 0.9475218658892128
[[108  13]
 [  5 217]]


0.9601769911504424

In [46]:
#Predict the response for test dataset
y_pred_hinge_test = clf.predict(x_hingeT)



# Model Accuracy for test data set 
print("Accuracy:",accuracy_score(y_test, y_pred_hinge_test))
# print confusion_matrix
print(confusion_matrix(y_test,y_pred_hinge_test))
# print f1_score
f1_score(y_test,y_pred_hinge_test)

Accuracy: 0.9
[[ 8  2]
 [ 0 10]]


0.9090909090909091

In [47]:
# Linear Kernel
clf = SVC(kernel='rbf', verbose=True, C=10) 

# Train the model using the train data set(cold features)
clf.fit(x_cold, y)

# Predict the response for train dataset
y_pred_cold_train = clf.predict(x_cold)



# Model Accuracy for train data set 
print("Accuracy:",accuracy_score(y, y_pred_cold_train))
# print confusion_matrix
print(confusion_matrix(y,y_pred_cold_train))
# print f1_score
f1_score(y,y_pred_cold_train)


[LibSVM]Accuracy: 0.7259475218658892
[[ 33  88]
 [  6 216]]


0.8212927756653992

In [48]:
#Predict the response for test dataset
y_pred_cold_test = clf.predict(x_coldT)

# Model Accuracy for test data set 
print("Accuracy:",accuracy_score(y_test, y_pred_cold_test))
# print confusion_matrix
print(confusion_matrix(y_test,y_pred_cold_test))
# print f1_score
f1_score(y_test,y_pred_cold_test)

Accuracy: 0.5
[[ 0 10]
 [ 0 10]]


0.6666666666666666

In [49]:
# concatenate to features for train data
x_hinge_cold=np.append(x_hinge,x_cold,axis=1)
# concatenate to features for test data
x_hinge_coldT=np.append(x_hingeT,x_coldT,axis=1)


In [50]:
clf = SVC(kernel='rbf', verbose=True, C=10) # Linear Kernel

# Train the model using the train data set(cold and hinge features)
clf.fit(x_hinge_cold, y)

# Predict the response for train dataset
y_pred_hinge_cold_train = clf.predict(x_hinge_cold)



# Model Accuracy for train data set 
print("Accuracy:",accuracy_score(y, y_pred_hinge_cold_train))
# print confusion_matrix
print(confusion_matrix(y,y_pred_hinge_cold_train))
# print f1_score
f1_score(y,y_pred_hinge_cold_train)


[LibSVM]Accuracy: 0.7317784256559767
[[ 39  82]
 [ 10 212]]


0.8217054263565892

In [51]:
#Predict the response for test dataset
y_pred_hinge_cold_test = clf.predict(x_hinge_coldT)



# Model Accuracy for test data set 
print("Accuracy:",accuracy_score(y_test, y_pred_hinge_cold_test))
# print confusion_matrix
print(confusion_matrix(y_test,y_pred_cold_test))
# print f1_score
f1_score(y_test,y_pred_cold_test)

Accuracy: 0.5
[[ 0 10]
 [ 0 10]]


0.6666666666666666